RK2
java-park-mail-ru/Apoj-09-2017 pull request #11
Opened 2017-10-31 17:56 UTC by ilyamoskalev

2017-11-03 12:07 UTC, d-nabokov requested changes

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/controllers/SessionController.java
> +        if (user == null || !service.checkSignin(user.getId(), body.getPassword())) {
Хочу `getId()` в отдельную переменную

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDao.java
> +    Long addUser(String login, String password, String email);
Nullability на возвращаемое значение и аргументы. Аналогично с имплементацией этого интерфейса

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDao.java
> +    void changeUserData(User user);
И тут

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDao.java
> +    User getUser(String login);
И здесь

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDao.java
> +    @Nullable Long getIdByLogin(@NotNull String login);
А ещё мне не нравится, что `@Nullable` то на строке выше, то на той же. Надо как-то к одному стилю прийти

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDaoImpl.java
> +                + "login = ?, "
Я не фанат того, что в классе `User` можно менять поля, но пусть будет так

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/db/UserDaoImpl.java
> +    private static final RowMapper<User> USER_MAPPER = (res, num) -> new User(res.getLong("id"),
Перенеси `new User(...` на новую строчку, а то теряется визуально

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/services/AccountService.java
> +    private final UserDao db;
Nullability полей

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/services/AccountService.java
> +    public void changePassword(User user, String password) {
Nullability аргументов здесь и далее

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/utils/Validator.java
> +            if (length > LOGIN_MAX_LENGTH) {
Это условие и предыдущее не могут выполняться одновременно. Можно сделать 
```
if (length < LOGIN_MIN_LENGTH) {
...
} else if (length > LOGIN_MAX_LENGTH) {
...
}

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/utils/Validator.java
> +            final Pattern p = Pattern.compile("^[a-z0-9_-]{1,}$");
Только сейчас заметил. Логин без заглавных букв - это разве норм?

2017-11-03 12:07 UTC, d-nabokov commented on src/main/java/application/utils/Validator.java
> +            if (length > PASSWORD_MAX_LENGTH) {
И здесь несовместимые условия

2017-11-03 12:07 UTC, d-nabokov commented on src/test/java/application/controller/ControllerTest.java
> +        service.clear();
Обязательно после каждого теста чистить базу, если ты её чистишь до каждого теста?

2017-11-03 12:07 UTC, Chocco-Crokko commented on src/test/java/application/controller/ControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON)
В `SessionController` есть строчка `public static final String JSON = "application/json";`. Предлагаю её заменить на `public static final String JSON = MediaType.APPLICATION_JSON;`

2017-11-03 12:07 UTC, Chocco-Crokko commented on src/test/resources/application.properties
> +spring.datasource.name=ilyadb
Перенос строки

2017-11-03 12:07 UTC, Chocco-Crokko commented on src/test/java/application/service/AccountServiceTest.java
> +public class AccountServiceTest {
Стиль написания тестов слишком отличается от стиля в `ControllerTest`. Надо более-менее привести к одному

2017-11-08 19:41 UTC, KSolovyev commented
Парни?

2017-11-12 16:37 UTC, pryahin commented
А пр-то будут мереть?

2017-11-12 17:09 UTC, merged