Develop
java-park-mail-ru/Apoj-09-2017 pull request #3
Opened 2017-09-19 22:03 UTC by ilyamoskalev

2017-09-19 22:28 UTC, KSolovyev requested changes
To be continued....

2017-09-19 22:28 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +        final Pattern p = Pattern.compile("^[-\\w.]+@([A-z0-9][-A-z0-9]+\\.)+[A-z]{2,4}$");
правильную регулярку на почту вы вряд ли придумаете. Так что здесь лучше проверить, что есть символ '@' и он в середине. На этом успокоиться и попробовать послать туда письмо с подтверждением. Письмо мы, конечно, вас заставлять посылать не будем, но регулярку надо убрать

2017-09-19 22:28 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +        final Pattern p = Pattern.compile("^[a-zA-Z0-9]{6,20}$");
6??? блин, много
И почему только буквы и цифры?

2017-09-19 22:28 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +    public static final String LOGIN_ERROR = "Invalid login ";
выглядит, как `private static`...

2017-09-19 22:28 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +    private static AccountService service;
не так это делается.
Во-первых, static надо убрать
Во-вторых, сервис нужно добавить в параметры контроллера
В-третьих, нужно добавить аннотацию `@Service` на AccountService - у вас уже сделано

Спринг вам сервис заинжектит, как параметр конструктора.

2017-09-20 15:21 UTC, couatl commented on src/main/java/application/utils/Validator.java
> +        final Pattern p = Pattern.compile("^[a-zA-Z0-9]{6,20}$");
6 - как раз для qwerty!
Потому что спец символы нас пугают, всякие инжекшн

2017-09-20 16:51 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +        final Pattern p = Pattern.compile("^[a-zA-Z0-9]{6,20}$");
откуда там они возьмутся??? Максимум, что случится: у вас база откажется вставлять эмоджи

2017-09-20 18:13 UTC, KSolovyev requested changes

2017-09-20 18:13 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +@CrossOrigin
нужно поставить конкретный домен, http://forntend.heroku.com - тот что шлет фронт в preflight-запросе

2017-09-20 19:10 UTC, d-nabokov requested changes

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/Application.java
> +    public UserDB dataBase() {
database - это одно слово

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/controllers/SessionController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new MessageResponse("Login or Email already exsists"));
exists

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/services/AccountService.java
> +        encoder = new BCryptPasswordEncoder();
Не нужно создавать ручками. Объявлены ведь `Bean`'ы. Нужно сделать, чтобы конструктор принимал `UserDB` и `PasswordEncoder`

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/controllers/SessionController.java
> +        if (httpSession.getAttribute("userId") == null) {
Заюзать константу

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/controllers/SessionController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(new MessageResponse("User already authorize"));
Было бы здорово все эти строки об ошибках вынести в класс-хелпер

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/utils/Validator.java
> +    private static final String LOGIN_ERROR = "Invalid login ";
Надо сообщать, что именно не так. Неверная длина, невалидные символы или ещё что

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/controllers/SessionController.java
> +        if (httpSession.getAttribute("userId") == null) {
И здесь константу

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/db/UserDB.java
> +    private static long id = 1;
Сделать `AtomicLong`

2017-09-20 19:10 UTC, d-nabokov commented on src/main/java/application/db/UserDB.java
> +        }
```java
for (User user : map.values()) {
  if (user.getLogin().equals(login)) {
    return user.getId();
  }
}
```
Ну и далее так

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/java/application/services/AccountService.java
> +        return encoder.matches(password, db.getUser(id).getPassword());
`db.getUser(id)` может вернуть `null`, тогда с `NullPointerException` упадёт. Нужны аннотации!

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/java/application/utils/Validator.java
> +        final Pattern p = Pattern.compile("(?=^.{8,}$)((?=.*\\d)|(?=.*\\W+))(?![.\\n])(?=.*[A-Z])(?=.*[a-z]).*$");
Может, пароль только на длину проверять?

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/resources/application.properties
> +server.port = ${PORT}
Гитхаб требует переноса строки

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/java/application/utils/responses/UserResponseWP.java
> +    @NotNull
Примитивы не нужно аннотировать на nullability. Они никогда не могут быть `null`

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/java/application/utils/responses/UserResponseWP.java
> +    private String login;
А почему логин с почтой не final?

2017-09-20 19:10 UTC, Chocco-Crokko commented on src/main/java/application/utils/requests/SignupRequest.java
> +    private String password;
Менять пароль в запросе выглядит немного странно

2017-09-20 20:06 UTC, ilyamoskalev commented on src/main/java/application/utils/requests/SignupRequest.java
> +    private String password;
Кто-нибудь, остановите этого парня)

2017-09-21 09:17 UTC, KSolovyev commented on src/main/java/application/utils/requests/SignupRequest.java
> +    private String password;
нет, нет, продолжай. Мне нравится

2017-09-21 13:15 UTC, ilyamoskalev commented on src/main/java/application/utils/requests/SignupRequest.java
> +    private String password;
@couatl @pryahin лукасы они тут свои ставят... Лучше бы frontend нормальный запилили...

2017-09-21 16:25 UTC, pryahin commented on src/main/java/application/utils/requests/SignupRequest.java
> +    private String password;
@ilyamoskalev фронт отличный

2017-09-22 21:19 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +    private static final String EXSISTS = "Login or Email already exists";
В слове "exist" только одна буква 's'

2017-09-22 21:20 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +    private static final String EMAIL_EXSISTS = "Login or Email already exists";
Странно, что переменная говорит о том, что почта уже существует, а в значении ещё и логин указан. Аналогично строка выше

2017-09-22 21:24 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +        if (httpSession.getAttribute("userId") == null) {
Убрал константу и добавил туда её значение? Странно, странно

2017-09-22 21:54 UTC, ilyamoskalev commented on src/main/java/application/controllers/SessionController.java
> +    private static final String EMAIL_EXSISTS = "Login or Email already exists";
это случайно вышло¯\_(ツ)_/¯

2017-09-22 21:54 UTC, ilyamoskalev commented on src/main/java/application/controllers/SessionController.java
> +        if (httpSession.getAttribute("userId") == null) {
и это тоже)

2017-09-24 19:26 UTC, KSolovyev requested changes

2017-09-24 19:26 UTC, KSolovyev commented on Apoj.iml
> +<?xml version="1.0" encoding="UTF-8"?>
.iml файлов не должно быть в проекте

2017-09-24 19:26 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +//@CrossOrigin(origins = {"https://gametes.herokuapp.com", "localhost:8080"})
?? почему закомментировано?

2017-09-24 19:26 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +    private static final String NOT_AUTHORIZE = "User not authorize";
Давайте сообщения об ошибках в отдельный файл

2017-09-24 19:26 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +        } else if (httpSession.getAttribute(USER_ID) != null) {
в таких местах else только мешает читать код. Давайте уберем его везде, где на предыдущей строке делается `return`

2017-09-24 19:26 UTC, KSolovyev commented on src/main/java/application/utils/Validator.java
> +            error += EMPTY_LOGIN;
давайте здесь лист возвращать, что ли. Конкатинированная строка выглядит странно

2017-09-24 19:33 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +//@CrossOrigin(origins = {"https://gametes.herokuapp.com", "localhost:8080"})
Это было для облегчения жизни фронтендеров.
Не с `https://gametes.herokuapp.com` не работало, а я так понимаю, что указывать локалхост не имеет смысла, потому что локалхост - это адрес машины, крутящейся на heroku, возможно, я не прав.
Но в любом случае в мастер не должно попадать закомменченное, да

2017-09-27 05:49 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +    @PostMapping(path = "/signup", consumes = Messages.JSON, produces = Messages.JSON)
JSON - это не сообщение

2017-09-27 06:48 UTC, d-nabokov requested changes

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(new MessageResponse(Messages.EXSISTS));
EXISTS
Ты рофлишь что ли?

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/db/UserDB.java
> +        return map.get(userId);
А если когда-нибудь придёт невалидный айдишник, то прога упадёт :)
Но будем думать, что валидация справится

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/db/UserDB.java
> +        map.put(id.get(), new User(id.get(), login, password, email));
`id.get()` нужно вынести перед этим в переменную, чтобы не вызывать два раза

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/utils/Messages.java
> +    public static final String EMAIL_EXSISTS = "Email already exist";
У тебя spellchecker не ругается на опечатки что ли?

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/utils/Validator.java
> +        if (login.length() > LOGIN_MAX_LENGTH) {
Длину вынести в переменную

2017-09-27 06:48 UTC, Chocco-Crokko commented on src/main/java/application/utils/Validator.java
> +        if (password.length() > PASSWORD_MAX_LENGTH) {
И здесь тоже

2017-10-03 18:41 UTC, KSolovyev commented
Мальчишки, девчонки, привет.
Как дела с замечаниями?

2017-10-04 15:42 UTC, couatl commented
Ну, ваши замечания поправлены!

2017-10-04 21:11 UTC, KSolovyev commented
надо поправить все замечания. Или вы мне предлагаете пробежаться по коду и дописать во всех местах, что я согласен? =)

2017-10-05 15:50 UTC, d-nabokov requested changes

2017-10-05 15:50 UTC, Chocco-Crokko commented on .travis.yml
> +    branch: develop
Было бы здорово перед открытием ПР в мастер отводить отдельную ветку. В ней надо устанавливать значения, относящиеся к ветке мастер, и делать ПР в него

2017-10-05 15:50 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +        if (httpSession.getAttribute(Messages.USER_ID) != null) {
`USER_ID` - это тоже не сообщение

2017-10-05 15:50 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +        return ResponseEntity.ok(new UserResponseWP(newUser));
По-моему лучше сделать конструктор `UserResponseWP`, который бы принимал `id` и `SignupRequest `

2017-10-05 15:50 UTC, Chocco-Crokko commented on src/main/java/application/controllers/SessionController.java
> +
Убери переводы лишние (супер важное замечание)

2017-10-05 15:50 UTC, Chocco-Crokko commented on src/main/java/application/db/UserDB.java
> +        if (map.containsKey(userId)) {
Если нет такого элемента, то `map.get()` вернёт `null`. Эта проверка лишняя

2017-10-05 15:50 UTC, Chocco-Crokko commented on src/main/java/application/utils/Validator.java
> +    private static final String SHORT_LOGIN = "Short login";
Хорошо бы сообщить, какой длины должен быть логин, то же с паролем

2017-10-05 17:31 UTC, couatl commented on src/main/java/application/utils/Validator.java
> +    private static final String SHORT_LOGIN = "Short login";
@_@ 
Ты рк написать дашь или не дашь?

2017-10-09 19:17 UTC, KSolovyev commented on src/main/java/application/controllers/SessionController.java
> +    @PostMapping(path = "/newpswrd", consumes = JSON, produces = JSON)
Tht Whch Hs N Vwls
![tht whch hs n vwls](https://user-images.githubusercontent.com/4122313/31354466-2c82a3fa-ad3f-11e7-86df-bb68991dec61.png)

2017-10-11 10:06 UTC, KSolovyev approved these changes

2017-10-11 10:07 UTC, merged

2017-10-11 10:07 UTC, KSolovyev commented
надо будет смержить мастер в девелоп